pipeline {
    // 使用 Docker 镜像 maven:3-alpine 进行构建
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        // 构建阶段
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        // 测试阶段
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    // 使用 JUnit 插件输出测试报告
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        // 交付阶段
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
